services:
  - type: web
    name: hackarena-backend
    runtime: node
    buildCommand: npm install && npm run migrate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: /opt/render/project/src/database/hackarena.db
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://your-frontend-domain.onrender.com
    healthCheckPath: /api/health
    disk:
      name: hackarena-data
      mountPath: /opt/render/project/src/database
      sizeGB: 1